### ISSUE TITLE
Cannot scroll if put SpringScrollView inside SafeAreaView

### ISSUE THREAD

**Issue by vinhtq** [bolan9999/react-native-spring-scrollview#12]
If we put SpringScrollView inside SafeAreaView then we cannot scroll anymore
```
return (
     <SafeAreaView>
          <SpringScrollView>

            {arr.map((i, index) =>
              <Text key={index}>
                Modify the '_contentCount','_bounces' and '_scrollEnabled' in
                BouncesExample.js to check if VerticalScrollView works well.
              </Text>
            )}
          </SpringScrollView>
     </SafeAreaView>
 )
```

**Comment by bolan9999** [comment]
I have checked it on both iOS and Android. And everything goes well. I guess that it is your style problem. Read the docs please:


Keep in mind that SpringScrollViews must have a bounded height in order to work, since they contain unbounded-height children into a bounded container (via a scroll interaction). In order to bound the height of a ScrollView, either set the height of the view directly (discouraged) or make sure all parent views have bounded height. SpringScrollViews default have a {flex:1} style, **please be sure its parent has abounded height**.

Try to fix it like this:
```
return (
     <SafeAreaView style={{flex:1}}>
          <SpringScrollView>
            {arr.map((i, index) =>
              <Text key={index}>
                Modify the '_contentCount','_bounces' and '_scrollEnabled' in
                BouncesExample.js to check if VerticalScrollView works well.
              </Text>
            )}
          </SpringScrollView>
     </SafeAreaView>
 )
```

**Comment by bolan9999** [comment]
And make sure you get the latest version: 2.0.2

**Comment by vinhtq** [comment]
I see now it works. Thank you for your help!
